export const PET_INTERACTION_GLOBAL_COOLDOWN_MS = 450;
export const PET_ACTION_TRIGGER_SAME_REASON_THROTTLE_MS = 700;
export const REPLY_COMPLETION_AFFECT_GLOBAL_COOLDOWN_RETRY_DELAY_MS =
  Math.max(PET_INTERACTION_GLOBAL_COOLDOWN_MS, PET_ACTION_TRIGGER_SAME_REASON_THROTTLE_MS) + 1;
