import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";

test("history, memory, automatic situation and user profile IPC are restricted and expose no file access bridge", async () => {
  const appSource = await readFile(join(process.cwd(), "src", "main", "app.ts"), "utf8");
  const preloadSource = await readFile(join(process.cwd(), "dist", "preload", "chat-preload.js"), "utf8");

  assert.match(appSource, /ipcMain\.handle\("history:list", \(event\) => \{\s+if \(!isChatSender\(event\) \|\| !historyStore\)/);
  assert.match(appSource, /ipcMain\.handle\("history:get", \(event, id: unknown\) => \{\s+if \(!isChatSender\(event\) \|\| !historyStore \|\| !isHistoryId\(id\)\)/);
  assert.match(appSource, /ipcMain\.handle\("history:clear", \(event\) => \{\s+if \(!isChatSender\(event\) \|\| !historyStore\)/);
  assert.match(appSource, /ipcMain\.handle\("memory:list", \(event\) => \{\s+if \(!isChatSender\(event\) \|\| !memoryStore\)/);
  assert.match(appSource, /ipcMain\.handle\("memory:create", \(event, draft: unknown\) => \{\s+const parsedDraft = parseMemoryCardDraft\(draft\);/);
  assert.match(appSource, /ipcMain\.handle\("memory:clear", \(event\) => \{\s+if \(!isChatSender\(event\) \|\| !memoryStore\)/);
  assert.match(appSource, /ipcMain\.handle\("userProfile:get", \(event\) => \{\s+if \(!isChatSender\(event\) \|\| !userProfileStore\)/);
  assert.match(appSource, /ipcMain\.handle\("userProfile:save", \(event, profile: unknown\) => \{\s+if \(!isChatSender\(event\) \|\| !userProfileStore\)/);
  assert.match(appSource, /ipcMain\.handle\("userProfile:clear", \(event\) => \{\s+if \(!isChatSender\(event\) \|\| !userProfileStore\)/);
  assert.match(appSource, /ipcMain\.handle\("automaticSituation:get", \(event\) => \{\s+if \(!isPetSender\(event\) \|\| !automaticSituationCoordinator\)/);
  assert.doesNotMatch(appSource, /ipcMain\.handle\("(?:dialogue|presence)Mode:(?:list|get|set)"/);
  assert.match(appSource, /event\.sender\.send\("chat:context-transparency", createChatContextTransparencyPayload\(\{/);
  assert.match(appSource, /event\.sender\.send\("chat:memory-activity", createChatMemoryActivityPayload\(\{/);
  assert.match(preloadSource, /exposeInMainWorld\("historyApi", historyApi\)/);
  assert.match(preloadSource, /exposeInMainWorld\("memoryApi", memoryApi\)/);
  assert.match(preloadSource, /exposeInMainWorld\("userProfileApi", userProfileApi\)/);
  assert.doesNotMatch(preloadSource, /exposeInMainWorld\("(?:dialogue|presence)ModeApi"/);
  assert.match(preloadSource, /onContextTransparency\(handler\) \{/);
  assert.match(preloadSource, /ipcRenderer\.on\("chat:context-transparency", listener\)/);
  assert.match(preloadSource, /hasExactKeys\(value, \["requestVersion", "contextBudget", "memory", "webSearch"\]\)/);
  assert.match(preloadSource, /hasExactKeys\(contextBudget, \[[\s\S]*"originalMessageCount"[\s\S]*"providerMessageCount"[\s\S]*"recentMessageCount"[\s\S]*\]\)/);
  assert.match(preloadSource, /hasExactKeys\(memory, \["injectionCount"\]\)/);
  assert.match(preloadSource, /hasExactKeys\(webSearch, \[[\s\S]*"included"[\s\S]*"citationCount"[\s\S]*\]\)/);
  assert.match(preloadSource, /onMemoryActivity\(handler\) \{/);
  assert.match(preloadSource, /ipcRenderer\.on\("chat:memory-activity", listener\)/);
  assert.match(preloadSource, /hasExactKeys\(value, \["requestVersion", "autoCapture", "injection", "contextBudget"\]\)/);
  assert.match(preloadSource, /hasExactKeys\(autoCapture, \[[\s\S]*"injectionBudget"[\s\S]*\]\)/);
  assert.doesNotMatch(preloadSource, /exposeInMainWorld\("ipcRenderer"/);
  assert.doesNotMatch(preloadSource, /historyPath|memoryPath|profilePath|presenceModePath|readFile|writeFile/);
  assert.doesNotMatch(preloadSource, /chat:context-transparency[\s\S]{0,900}(content|cards|prompt|providerMessages|safeQuery|snippet|apiKey|memoryPath)/);
  assert.doesNotMatch(preloadSource, /chat:memory-activity[\s\S]{0,800}(content|cards|prompt|providerMessages|apiKey|memoryPath)/);
});
